name: core_ui
description: A Flutter design system package with design tokens and basic components.
version: 0.0.1
homepage: https://github.com/ripplearc/coreui
repository: https://github.com/ripplearc/coreui.git
publish_to: https://pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0  # For SVG support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: IBMPlexSansHebrew
      fonts:
        - asset: assets/fonts/IBMPlexSansHebrew-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansHebrew-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansHebrew-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansHebrew-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansHebrew-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansHebrew-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansHebrew-Thin.ttf
          weight: 100
