name: ripplearc_coreui
description: A Flutter design system package with design tokens and basic components.
version: 0.3.7
homepage: https://github.com/ripplearc/coreui
repository: https://github.com/ripplearc/coreui.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  lottie: ^3.3.1
  ripplearc_linter: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/letter_avatars/
    - assets/animations/

  fonts:
    - family: Roboto
      fonts:
        - asset: test/assets/fonts/Roboto-Regular.ttf
        - asset: test/assets/fonts/Roboto-Medium.ttf
        - asset: test/assets/fonts/Roboto-Bold.ttf
