name: Golden Tests

on: [ push ]

jobs:
  golden_test:
    name: Run Golden Tests
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Golden Tests
        run: |
          flutter test test/components/*
          flutter test test/theme/*
          flutter test test/notifications/*

      - name: Upload Golden Images
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: golden-images
          path: test/**/goldens/*.png
          retention-days: 5
          if-no-files-found: error 